### ISSUE TITLE
Conflicting migrations detected

### ISSUE THREAD

**Issue by SilmarillionUA** [studybuffalo/django-flexible-subscriptions#142]
`CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0006_add_slugs, 0003_stateorder in subscriptions).` while running migrate command.

**Comment by studybuffalo** [comment]
Was this a migration from scratch or an upgrade from a previous version? Any additional error details? I am able to run all migrations in testing and the sandbox, so not able to figure out what is going on in this case.

The `0003_stateorder` bit is curious because that is not a migration in `django-flexible-subscriptions` - any chance there is a conflict with another migration in another app?

**Comment by studybuffalo** [comment]
Closing issue for now - feel free to reopen if more details can be provided.

**Comment by priyadhoundiyal** [comment]
Hey @SilmarillionUA, I was also getting this error
When @studybuffalo suggested this

> The 0003_stateorder bit is curious because that is not a migration in django-flexible-subscriptions - any chance there is a conflict with another migration in another app?

I checked and realised I had installed both `django-subscriptions` and `django-flexible-subscriptions`
and saw that on doing `python manage.py showmigrations subscriptions` I was getting migrations from both apps which gave me the migration conflict
Uninstalling both packages, then reinstalling `django-flexible-subscriptions` worked for me
Leaving this here in case it helps someone :)
